(() => {
  const OWNER='system_admin';
  const isDashboard=()=>state.profile?.role===OWNER&&state.view==='dashboard';
  const images=e=>Array.from(e.clipboardData?.items||[]).filter(x=>x.kind==='file'&&/^image\//i.test(x.type||'')).map((x,i)=>{const f=x.getAsFile();if(!f)return null;const ext=(f.type||'image/png').split('/')[1]||'png';return new File([f],`clipboard-${Date.now()}-${i}.${ext}`,{type:f.type||'image/png',lastModified:Date.now()});}).filter(Boolean);
  function apply(input,files){const dt=new DataTransfer(),seen=new Set();[...Array.from(input.files||[]),...files].forEach(f=>{const k=`${f.name}:${f.size}:${f.lastModified}`;if(!seen.has(k)){seen.add(k);dt.items.add(f);}});input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));}
  function paste(e,id,input,zone){const files=images(e);if(!files.length)return;e.preventDefault();apply(input,files);zone.classList.add('ready');zone.innerHTML=`<strong>${files.length} screenshot${files.length===1?'':'s'} pasted</strong><span>Ready. Click “Add During” to save.</span>`;toast(`${files.length} screenshot${files.length===1?'':'s'} pasted into During evidence.`);}
  function install(){if(!isDashboard())return;document.querySelectorAll('[data-during-form]').forEach(form=>{if(form.dataset.pasteReady==='1')return;form.dataset.pasteReady='1';const id=form.dataset.duringForm,input=form.querySelector(`[data-during-file="${id}"]`);if(!input)return;const z=document.createElement('div');z.className='ww-paste-evidence';z.tabIndex=0;z.dataset.pasteTask=id;z.innerHTML='<strong>Paste screenshot here</strong><span>Copy a screenshot, click here, then press Ctrl+V. Choose Files still works too.</span>';input.insertAdjacentElement('beforebegin',z);z.onclick=()=>z.focus();z.addEventListener('paste',e=>paste(e,id,input,z));});}
  document.addEventListener('paste',e=>{if(!isDashboard()||!images(e).length||e.target?.closest?.('[data-paste-task]'))return;const forms=[...document.querySelectorAll('[data-during-form]')].filter(f=>!f.closest('.is-disabled'));if(forms.length!==1){if(forms.length>1)toast('Click the paste box of the task where you want to attach the screenshot.','error');return;}const f=forms[0],id=f.dataset.duringForm,input=f.querySelector(`[data-during-file="${id}"]`),z=f.querySelector(`[data-paste-task="${id}"]`);if(input&&z)paste(e,id,input,z);},true);
  const mo=new MutationObserver(install);mo.observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(install);
})();